default_pulling_interval: 10
token: ""
platform_host_url: "http://localhost:8080"
plugins: 
  - type: s3
    name: s3_adapter
    bucket: "odd-ge-adapter"
    results_key: ""
    suites_key: ""
    aws_region: ""
    aws_access_key_id: ""
    aws_secret_access_key: ""